import { twColors } from "./styles";

export type ThemeType = {
  [key: string]: keyof typeof twColors;
};

const defaultTheme: ThemeType = {
  "--color-text-primary": "neutral-900",
  "--color-text-secondary": "neutral-500",
  "--color-accent": "purple-500",
  "--color-primary": "neutral-900",
  "--color-secondary": "neutral-500",
  "--color-danger": "rose-500",
  "--color-warning": "amber-500",
  "--color-success": "teal-500",
  "--color-info": "cyan-500",
  "--color-link": "blue-500",
  "--color-background": "white",
  "--color-foreground": "neutral-50",
  "--color-input": "neutral-300",
  "--color-separator": "neutral-200",
  "--color-hint": "neutral-100",
  "--color-focus": "blue-500",
  "--color-text-primary-dark": "white",
  "--color-text-secondary-dark": "neutral-400",
  "--color-accent-dark": "purple-400",
  "--color-primary-dark": "white",
  "--color-secondary-dark": "neutral-400",
  "--color-danger-dark": "rose-400",
  "--color-warning-dark": "amber-400",
  "--color-success-dark": "teal-400",
  "--color-info-dark": "cyan-400",
  "--color-link-dark": "blue-400",
  "--color-background-dark": "neutral-900",
  "--color-foreground-dark": "neutral-800",
  "--color-input-dark": "neutral-700",
  "--color-separator-dark": "neutral-800",
  "--color-hint-dark": "neutral-950",
  "--color-focus-dark": "blue-400",
};

const classic: ThemeType = {
  "--color-text-primary": "slate-900",
  "--color-text-secondary": "slate-500",
  "--color-accent": "blue-600",
  "--color-primary": "blue-600",
  "--color-secondary": "slate-500",
  "--color-danger": "rose-500",
  "--color-warning": "amber-500",
  "--color-success": "teal-500",
  "--color-info": "cyan-500",
  "--color-link": "blue-500",
  "--color-background": "slate-50",
  "--color-foreground": "white",
  "--color-input": "slate-300",
  "--color-separator": "slate-200",
  "--color-hint": "slate-100",
  "--color-focus": "blue-500",
  "--color-text-primary-dark": "white",
  "--color-text-secondary-dark": "slate-400",
  "--color-accent-dark": "purple-400",
  "--color-primary-dark": "white",
  "--color-secondary-dark": "slate-400",
  "--color-danger-dark": "rose-400",
  "--color-warning-dark": "amber-400",
  "--color-success-dark": "teal-400",
  "--color-info-dark": "cyan-400",
  "--color-link-dark": "blue-400",
  "--color-background-dark": "slate-900",
  "--color-foreground-dark": "slate-800",
  "--color-input-dark": "slate-700",
  "--color-separator-dark": "slate-800",
  "--color-hint-dark": "slate-950",
  "--color-focus-dark": "blue-400",
};

const minty: ThemeType = {
  "--color-text-primary": "slate-900",
  "--color-text-secondary": "slate-500",
  "--color-accent": "teal-500",
  "--color-primary": "teal-500",
  "--color-secondary": "slate-500",
  "--color-danger": "rose-500",
  "--color-warning": "amber-500",
  "--color-success": "teal-500",
  "--color-info": "cyan-500",
  "--color-link": "blue-500",
  "--color-background": "white",
  "--color-foreground": "slate-50",
  "--color-input": "slate-300",
  "--color-separator": "slate-200",
  "--color-hint": "slate-100",
  "--color-focus": "blue-500",
  "--color-text-primary-dark": "white",
  "--color-text-secondary-dark": "slate-400",
  "--color-accent-dark": "teal-400",
  "--color-primary-dark": "white",
  "--color-secondary-dark": "slate-400",
  "--color-danger-dark": "rose-400",
  "--color-warning-dark": "amber-400",
  "--color-success-dark": "teal-400",
  "--color-info-dark": "cyan-400",
  "--color-link-dark": "blue-400",
  "--color-background-dark": "slate-900",
  "--color-foreground-dark": "slate-800",
  "--color-input-dark": "slate-700",
  "--color-separator-dark": "slate-800",
  "--color-hint-dark": "slate-950",
  "--color-focus-dark": "blue-400",
};




export const themes: { [key: string]: ThemeType } = {
  default: defaultTheme,
  classic,
  minty,
};
